### ISSUE TITLE
Activer l'audio des mp4 on expand

### ISSUE THREAD

**Issue by Grivel-l** [Grivel-l/101-memes#55]

**Comment by Grivel-l** [comment]
:+1: I got this

**Comment by julien-marquet** [comment]
un peu plus de logs :  
```
index.js:2178 Warning: Failed prop type: The prop `media` is marked as required in `Media`, but its value is `undefined`.
    in Media (created by Connect(Media))
    in Connect(Media) (at MediaBlock.js:11)
    in div (at MediaBlock.js:10)
    in MediaBlock (at App.js:56)
    in div (at App.js:87)
    in div (at App.js:86)
    in div (at App.js:84)
    in App (created by Connect(App))
    in Connect(App) (at index.js:24)
    in Provider (at index.js:23)
__stack_frame_overlay_proxy_console__ @ index.js:2178
printWarning @ warning.js:33
warning @ warning.js:57
checkPropTypes @ checkPropTypes.js:52
validatePropTypes @ react.development.js:1233
createElementWithValidation @ react.development.js:1321
render @ connectAdvanced.js:243
finishClassComponent @ react-dom.development.js:8389
updateClassComponent @ react-dom.development.js:8357
beginWork @ react-dom.development.js:8982
performUnitOfWork @ react-dom.development.js:11814
workLoop @ react-dom.development.js:11843
renderRoot @ react-dom.development.js:11874
performWorkOnRoot @ react-dom.development.js:12449
performWork @ react-dom.development.js:12370
performSyncWork @ react-dom.development.js:12347
requestWork @ react-dom.development.js:12247
scheduleWorkImpl @ react-dom.development.js:12122
scheduleWork @ react-dom.development.js:12082
enqueueSetState @ react-dom.development.js:6644
./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:238
onStateChange @ connectAdvanced.js:205
dispatch @ redux.js:221
(anonymous) @ middleware.js:66
dispatch @ redux.js:563
(anonymous) @ utils.js:250
(anonymous) @ proc.js:489
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
runPutEffect @ proc.js:486
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
Promise.then (async)
resolvePromise @ proc.js:450
runCallEffect @ proc.js:517
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
(anonymous) @ proc.js:499
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
(anonymous) @ channel.js:185
emit @ channel.js:26
(anonymous) @ middleware.js:67
publishMedia @ postbutton.js:17
publishMedia @ PostButton.js:50
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:201
executeDispatch @ react-dom.development.js:466
executeDispatchesInOrder @ react-dom.development.js:485
executeDispatchesAndRelease @ react-dom.development.js:586
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:597
forEachAccumulated @ react-dom.development.js:567
runEventsInBatch @ react-dom.development.js:728
runExtractedEventsInBatch @ react-dom.development.js:737
handleTopLevel @ react-dom.development.js:4201
batchedUpdates @ react-dom.development.js:12537
batchedUpdates @ react-dom.development.js:1939
dispatchEvent @ react-dom.development.js:4282
interactiveUpdates @ react-dom.development.js:12592
interactiveUpdates @ react-dom.development.js:1958
dispatchInteractiveEvent @ react-dom.development.js:4259
Media.js:20 Uncaught TypeError: Cannot read property '_id' of undefined
    at Media.shouldComponentUpdate (Media.js:20)
    at checkShouldComponentUpdate (react-dom.development.js:6696)
    at updateClassInstance (react-dom.development.js:7208)
    at updateClassComponent (react-dom.development.js:8345)
    at beginWork (react-dom.development.js:8982)
    at performUnitOfWork (react-dom.development.js:11814)
    at workLoop (react-dom.development.js:11843)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
    at invokeGuardedCallback (react-dom.development.js:187)
    at replayUnitOfWork (react-dom.development.js:11318)
    at renderRoot (react-dom.development.js:11885)
    at performWorkOnRoot (react-dom.development.js:12449)
    at performWork (react-dom.development.js:12370)
    at performSyncWork (react-dom.development.js:12347)
    at requestWork (react-dom.development.js:12247)
    at scheduleWorkImpl (react-dom.development.js:12122)
    at scheduleWork (react-dom.development.js:12082)
    at Object.enqueueSetState (react-dom.development.js:6644)
    at Connect../node_modules/react/cjs/react.development.js.Component.setState (react.development.js:238)
    at Connect.onStateChange (connectAdvanced.js:205)
    at dispatch (redux.js:221)
    at middleware.js:66
    at dispatch (redux.js:563)
    at utils.js:250
    at proc.js:489
    at exec (scheduler.js:19)
    at flush (scheduler.js:60)
    at asap (scheduler.js:33)
    at runPutEffect (proc.js:486)
    at runEffect (proc.js:435)
    at next (proc.js:315)
    at currCb (proc.js:388)
shouldComponentUpdate @ Media.js:20
checkShouldComponentUpdate @ react-dom.development.js:6696
updateClassInstance @ react-dom.development.js:7208
updateClassComponent @ react-dom.development.js:8345
beginWork @ react-dom.development.js:8982
performUnitOfWork @ react-dom.development.js:11814
workLoop @ react-dom.development.js:11843
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
replayUnitOfWork @ react-dom.development.js:11318
renderRoot @ react-dom.development.js:11885
performWorkOnRoot @ react-dom.development.js:12449
performWork @ react-dom.development.js:12370
performSyncWork @ react-dom.development.js:12347
requestWork @ react-dom.development.js:12247
scheduleWorkImpl @ react-dom.development.js:12122
scheduleWork @ react-dom.development.js:12082
enqueueSetState @ react-dom.development.js:6644
./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:238
onStateChange @ connectAdvanced.js:205
dispatch @ redux.js:221
(anonymous) @ middleware.js:66
dispatch @ redux.js:563
(anonymous) @ utils.js:250
(anonymous) @ proc.js:489
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
runPutEffect @ proc.js:486
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
Promise.then (async)
resolvePromise @ proc.js:450
runCallEffect @ proc.js:517
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
(anonymous) @ proc.js:499
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
(anonymous) @ channel.js:185
emit @ channel.js:26
(anonymous) @ middleware.js:67
publishMedia @ postbutton.js:17
publishMedia @ PostButton.js:50
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:201
executeDispatch @ react-dom.development.js:466
executeDispatchesInOrder @ react-dom.development.js:485
executeDispatchesAndRelease @ react-dom.development.js:586
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:597
forEachAccumulated @ react-dom.development.js:567
runEventsInBatch @ react-dom.development.js:728
runExtractedEventsInBatch @ react-dom.development.js:737
handleTopLevel @ react-dom.development.js:4201
batchedUpdates @ react-dom.development.js:12537
batchedUpdates @ react-dom.development.js:1939
dispatchEvent @ react-dom.development.js:4282
interactiveUpdates @ react-dom.development.js:12592
interactiveUpdates @ react-dom.development.js:1958
dispatchInteractiveEvent @ react-dom.development.js:4259
index.js:2178 The above error occurred in the <Media> component:
    in Media (created by Connect(Media))
    in Connect(Media) (at MediaBlock.js:11)
    in div (at MediaBlock.js:10)
    in MediaBlock (at App.js:56)
    in div (at App.js:87)
    in div (at App.js:86)
    in div (at App.js:84)
    in App (created by Connect(App))
    in Connect(App) (at index.js:24)
    in Provider (at index.js:23)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
__stack_frame_overlay_proxy_console__ @ index.js:2178
logCapturedError @ react-dom.development.js:9643
logError @ react-dom.development.js:9682
commitErrorLogging @ react-dom.development.js:9895
commitAllLifeCycles @ react-dom.development.js:11459
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
commitRoot @ react-dom.development.js:11594
completeRoot @ react-dom.development.js:12502
performWorkOnRoot @ react-dom.development.js:12452
performWork @ react-dom.development.js:12370
performSyncWork @ react-dom.development.js:12347
requestWork @ react-dom.development.js:12247
scheduleWorkImpl @ react-dom.development.js:12122
scheduleWork @ react-dom.development.js:12082
enqueueSetState @ react-dom.development.js:6644
./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:238
onStateChange @ connectAdvanced.js:205
dispatch @ redux.js:221
(anonymous) @ middleware.js:66
dispatch @ redux.js:563
(anonymous) @ utils.js:250
(anonymous) @ proc.js:489
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
runPutEffect @ proc.js:486
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
Promise.then (async)
resolvePromise @ proc.js:450
runCallEffect @ proc.js:517
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
(anonymous) @ proc.js:499
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
(anonymous) @ channel.js:185
emit @ channel.js:26
(anonymous) @ middleware.js:67
publishMedia @ postbutton.js:17
publishMedia @ PostButton.js:50
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:201
executeDispatch @ react-dom.development.js:466
executeDispatchesInOrder @ react-dom.development.js:485
executeDispatchesAndRelease @ react-dom.development.js:586
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:597
forEachAccumulated @ react-dom.development.js:567
runEventsInBatch @ react-dom.development.js:728
runExtractedEventsInBatch @ react-dom.development.js:737
handleTopLevel @ react-dom.development.js:4201
batchedUpdates @ react-dom.development.js:12537
batchedUpdates @ react-dom.development.js:1939
dispatchEvent @ react-dom.development.js:4282
interactiveUpdates @ react-dom.development.js:12592
interactiveUpdates @ react-dom.development.js:1958
dispatchInteractiveEvent @ react-dom.development.js:4259
index.js:2178 uncaught at publishMedia TypeError: Cannot read property '_id' of undefined
    at Media.shouldComponentUpdate (http://localhost:3000/static/js/bundle.js:46035:193)
    at checkShouldComponentUpdate (http://localhost:3000/static/js/bundle.js:13094:35)
    at updateClassInstance (http://localhost:3000/static/js/bundle.js:13606:24)
    at updateClassComponent (http://localhost:3000/static/js/bundle.js:14743:22)
    at beginWork (http://localhost:3000/static/js/bundle.js:15380:16)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:18212:16)
    at workLoop (http://localhost:3000/static/js/bundle.js:18241:26)
    at renderRoot (http://localhost:3000/static/js/bundle.js:18272:9)
    at performWorkOnRoot (http://localhost:3000/static/js/bundle.js:18847:24)
    at performWork (http://localhost:3000/static/js/bundle.js:18768:9)
    at performSyncWork (http://localhost:3000/static/js/bundle.js:18745:5)
    at requestWork (http://localhost:3000/static/js/bundle.js:18645:7)
    at scheduleWorkImpl (http://localhost:3000/static/js/bundle.js:18520:13)
    at scheduleWork (http://localhost:3000/static/js/bundle.js:18480:12)
    at Object.enqueueSetState (http://localhost:3000/static/js/bundle.js:13042:7)
    at Connect../node_modules/react/cjs/react.development.js.Component.setState (http://localhost:3000/static/js/bundle.js:32759:16)
    at Connect.onStateChange (http://localhost:3000/static/js/bundle.js:29166:16)
    at dispatch (http://localhost:3000/static/js/bundle.js:36572:7)
    at http://localhost:3000/static/js/bundle.js:34769:22
    at dispatch (http://localhost:3000/static/js/bundle.js:36914:28)
    at http://localhost:3000/static/js/bundle.js:36273:12
    at http://localhost:3000/static/js/bundle.js:35296:52
    at exec (http://localhost:3000/static/js/bundle.js:35936:5)
    at flush (http://localhost:3000/static/js/bundle.js:35977:5)
    at asap (http://localhost:3000/static/js/bundle.js:35950:5)
    at runPutEffect (http://localhost:3000/static/js/bundle.js:35293:69)
    at runEffect (http://localhost:3000/static/js/bundle.js:35242:307)
    at next (http://localhost:3000/static/js/bundle.js:35122:9)
    at currCb (http://localhost:3000/static/js/bundle.js:35195:7)
```

**Comment by julien-marquet** [comment]
je l'ai plus ce bug
